# Generated by Django 2.1.3 on 2018-12-22 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='reg_details',
        ),
    ]
