# Generated by Django 2.1.3 on 2018-12-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=40)),
                ('winner', models.IntegerField()),
                ('group_name', models.CharField(max_length=10)),
            ],
        ),
    ]
