# Generated by Django 2.1.3 on 2018-12-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0002_teams'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
