# Generated by Django 2.1.3 on 2018-12-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0003_auto_20181220_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='pointsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(max_length=10)),
                ('team_name', models.CharField(max_length=40)),
                ('group_name', models.CharField(max_length=10)),
                ('matches', models.IntegerField()),
                ('won', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('nrr', models.IntegerField()),
            ],
        ),
    ]
