# Generated by Django 2.1.3 on 2018-12-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0004_pointstable'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstable',
            name='pts',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
