# Generated by Django 2.1.3 on 2018-12-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0005_pointstable_pts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pointsTable',
            new_name='points_table',
        ),
    ]
