# Generated by Django 2.1.3 on 2018-12-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0006_auto_20181221_0933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
