# Generated by Django 2.1.3 on 2018-12-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0007_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points_table',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='points_table',
            name='team_name',
        ),
        migrations.AlterField(
            model_name='points_table',
            name='team_id',
            field=models.ForeignKey(on_delete='CASCADE', to='bcc.Team'),
        ),
    ]
