# Generated by Django 2.1.3 on 2018-12-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0008_auto_20181221_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='points_table',
            name='id',
        ),
        migrations.AlterField(
            model_name='points_table',
            name='team_id',
            field=models.OneToOneField(on_delete='CASCADE', primary_key='True', serialize=False, to='bcc.Team'),
        ),
    ]
