# Generated by Django 2.1.3 on 2018-12-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0010_schedule_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_2019',
            name='match_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule_2019',
            name='team_1',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='team1toteam', to='bcc.Team'),
        ),
        migrations.AlterField(
            model_name='schedule_2019',
            name='team_2',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='team2toteam', to='bcc.Team'),
        ),
    ]
