# Generated by Django 2.1.3 on 2018-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0011_auto_20181222_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_2019',
            name='id',
        ),
        migrations.AlterField(
            model_name='schedule_2019',
            name='match_id',
            field=models.IntegerField(primary_key='True', serialize=False),
        ),
    ]
