# Generated by Django 2.1.3 on 2018-12-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0012_auto_20181222_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='player_info',
            fields=[
                ('player_id', models.CharField(max_length=10, primary_key='True', serialize=False)),
                ('player_fname', models.CharField(max_length=50)),
                ('player_lname', models.CharField(max_length=50)),
                ('player_F_name', models.CharField(default='XYZ', max_length=50)),
                ('bowling_style', models.CharField(default='Right Handed Batsman', max_length=50)),
                ('batting_style', models.CharField(default='Right-arm-fast-medium', max_length=50)),
                ('player_role', models.CharField(choices=[('Batsman', 'BATSMAN'), ('Bowler', 'BOWLER'), ('WicketKeeper', 'WICKETKEEPER'), ('LegSpinner', 'LEGSPINNER')], default='Batsman', max_length=30)),
                ('team_id', models.ForeignKey(on_delete='models.CASCADE', to='bcc.Team')),
            ],
        ),
    ]
