# Generated by Django 2.1.3 on 2018-12-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0013_player_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_info',
            name='player_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
