# Generated by Django 2.1.3 on 2018-12-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0015_auto_20181224_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='Bt_fours',
            field=models.IntegerField(default=14),
        ),
        migrations.AlterField(
            model_name='batting',
            name='Bt_matches',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='batting',
            name='player_id',
            field=models.OneToOneField(on_delete='models.CASCADE', to='bcc.player_info'),
        ),
    ]
