# Generated by Django 2.1.3 on 2018-12-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0016_auto_20181224_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_info',
            name='team_id',
            field=models.ForeignKey(null='True', on_delete='models.CASCADE', to='bcc.Team'),
        ),
    ]
