# Generated by Django 2.1.3 on 2018-12-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0017_auto_20181224_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='bowling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bw_runs', models.IntegerField(default=247)),
                ('Bw_balls', models.IntegerField(default=150)),
                ('Bw_innings', models.IntegerField(default=6)),
                ('Bt_wicket', models.IntegerField(default=10)),
                ('player_id', models.OneToOneField(on_delete='models.CASCADE', to='bcc.player_info')),
            ],
        ),
    ]
