# Generated by Django 2.1.3 on 2018-12-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0018_bowling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batting',
            name='Bt_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batting',
            name='Bt_fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batting',
            name='Bt_innings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batting',
            name='Bt_matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='batting',
            name='Bt_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='Bt_wicket',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='Bw_balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='Bw_innings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bowling',
            name='Bw_runs',
            field=models.IntegerField(default=0),
        ),
    ]
