# Generated by Django 2.1.3 on 2018-12-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0019_auto_20181224_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bowling',
            old_name='Bt_wicket',
            new_name='Bw_matches',
        ),
        migrations.AddField(
            model_name='bowling',
            name='Bw_wickets',
            field=models.IntegerField(default=0),
        ),
    ]
