# Generated by Django 2.1.3 on 2018-12-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0020_auto_20181225_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points_table',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='nrr',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='pts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points_table',
            name='won',
            field=models.IntegerField(default=0),
        ),
    ]
