# Generated by Django 2.1.3 on 2019-01-17 13:42

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0022_playing_xi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playing_xi',
            name='players',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('VK', 'Virat Kohli'), ('ST', 'Sachin'), ('RS', 'Rohit Sharma'), ('MS', 'Mohammed Shami')], max_length=11),
        ),
    ]
