# Generated by Django 2.1.3 on 2019-01-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0023_auto_20190117_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='cheksum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheksum_id', models.IntegerField()),
            ],
        ),
    ]
