# Generated by Django 2.1.3 on 2019-01-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bcc', '0024_cheksum'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cheksum',
        ),
    ]
